class Doctor {
  final String id;
  final String name;
  final String speciality;
  final String imageUrl;
  final double rating;
  final int experience;
  final bool isAvailable;

  Doctor({
    required this.id,
    required this.name,
    required this.speciality,
    required this.imageUrl,
    required this.rating,
    required this.experience,
    this.isAvailable = true,
  });

  static List<Doctor> getDoctors() {
    return [
      Doctor(
        id: 'doc_001',
        name: 'Dr. Sarah Johnson',
        speciality: 'Cardiologist',
        imageUrl: 'https://i.pravatar.cc/150?img=5',
        rating: 4.8,
        experience: 12,
        isAvailable: true,
      ),
      Doctor(
        id: 'doc_002',
        name: 'Dr. Michael Brown',
        speciality: 'Dermatologist',
        imageUrl: 'https://i.pravatar.cc/150?img=12',
        rating: 4.7,
        experience: 10,
        isAvailable: true,
      ),
      Doctor(
        id: 'doc_003',
        name: 'Dr. Emily Davis',
        speciality: 'Neurologist',
        imageUrl: 'https://i.pravatar.cc/150?img=20',
        rating: 4.9,
        experience: 15,
        isAvailable: false,
      ),
      Doctor(
        id: 'doc_004',
        name: 'Dr. James Wilson',
        speciality: 'Orthopedic',
        imageUrl: 'https://i.pravatar.cc/150?img=25',
        rating: 4.6,
        experience: 8,
        isAvailable: true,
      ),
      Doctor(
        id: 'doc_005',
        name: 'Dr. Olivia Martinez',
        speciality: 'Pediatrician',
        imageUrl: 'https://i.pravatar.cc/150?img=32',
        rating: 4.8,
        experience: 11,
        isAvailable: true,
      ),
      Doctor(
        id: 'doc_006',
        name: 'Dr. William Anderson',
        speciality: 'ENT Specialist',
        imageUrl: 'https://i.pravatar.cc/150?img=36',
        rating: 4.5,
        experience: 9,
        isAvailable: false,
      ),
      Doctor(
        id: 'doc_007',
        name: 'Dr. Sophia Taylor',
        speciality: 'Gynecologist',
        imageUrl: 'https://i.pravatar.cc/150?img=41',
        rating: 4.9,
        experience: 14,
        isAvailable: true,
      ),
      Doctor(
        id: 'doc_008',
        name: 'Dr. Daniel Thomas',
        speciality: 'Psychiatrist',
        imageUrl: 'https://i.pravatar.cc/150?img=47',
        rating: 4.7,
        experience: 13,
        isAvailable: true,
      ),
      Doctor(
        id: 'doc_009',
        name: 'Dr. Ava Moore',
        speciality: 'Dentist',
        imageUrl: 'https://i.pravatar.cc/150?img=49',
        rating: 4.6,
        experience: 7,
        isAvailable: false,
      ),
      Doctor(
        id: 'doc_010',
        name: 'Dr. Benjamin Harris',
        speciality: 'Ophthalmologist',
        imageUrl: 'https://i.pravatar.cc/150?img=52',
        rating: 4.8,
        experience: 16,
        isAvailable: true,
      ),
      Doctor(
        id: 'doc_011',
        name: 'Dr. Mia Clark',
        speciality: 'General Physician',
        imageUrl: 'https://i.pravatar.cc/150?img=56',
        rating: 4.5,
        experience: 6,
        isAvailable: true,
      ),
      Doctor(
        id: 'doc_012',
        name: 'Dr. Ethan Lewis',
        speciality: 'Urologist',
        imageUrl: 'https://i.pravatar.cc/150?img=58',
        rating: 4.7,
        experience: 12,
        isAvailable: true,
      ),
      Doctor(
        id: 'doc_013',
        name: 'Dr. Charlotte Walker',
        speciality: 'Endocrinologist',
        imageUrl: 'https://i.pravatar.cc/150?img=60',
        rating: 4.8,
        experience: 10,
        isAvailable: false,
      ),
      Doctor(
        id: 'doc_014',
        name: 'Dr. Alexander Hall',
        speciality: 'Oncologist',
        imageUrl: 'https://i.pravatar.cc/150?img=62',
        rating: 4.9,
        experience: 18,
        isAvailable: true,
      ),
      Doctor(
        id: 'doc_015',
        name: 'Dr. Amelia Allen',
        speciality: 'Pulmonologist',
        imageUrl: 'https://i.pravatar.cc/150?img=64',
        rating: 4.6,
        experience: 11,
        isAvailable: true,
      ),
      Doctor(
        id: 'doc_016',
        name: 'Dr. Matthew Young',
        speciality: 'Nephrologist',
        imageUrl: 'https://i.pravatar.cc/150?img=66',
        rating: 4.7,
        experience: 9,
        isAvailable: false,
      ),
      Doctor(
        id: 'doc_017',
        name: 'Dr. Harper King',
        speciality: 'Rheumatologist',
        imageUrl: 'https://i.pravatar.cc/150?img=68',
        rating: 4.8,
        experience: 13,
        isAvailable: true,
      ),
      Doctor(
        id: 'doc_018',
        name: 'Dr. Lucas Scott',
        speciality: 'Gastroenterologist',
        imageUrl: 'https://i.pravatar.cc/150?img=70',
        rating: 4.9,
        experience: 17,
        isAvailable: true,
      ),
      Doctor(
        id: 'doc_019',
        name: 'Dr. Evelyn Green',
        speciality: 'Radiologist',
        imageUrl: 'https://i.pravatar.cc/150?img=72',
        rating: 4.5,
        experience: 8,
        isAvailable: true,
      ),
      Doctor(
        id: 'doc_020',
        name: 'Dr. Henry Adams',
        speciality: 'Surgeon',
        imageUrl: 'https://i.pravatar.cc/150?img=74',
        rating: 5.0,
        experience: 20,
        isAvailable: false,
      ),
    ];
  }
}
